version: "3.9"
services:
  app: 
    build: ./infra/php
    volumes:
      - ./src:/data

  # nginx設定
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  # mysql設定
  db:
    build: ./infra/mysql
    ports:
      - "4306:3306"
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: